# Generated by Django 4.1 on 2023-04-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_location_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="description",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
