# Generated by Django 4.1 on 2023-04-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_skill_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["created"]},
        ),
    ]
