# Generated by Django 4.1 on 2023-03-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_review_tag_delete_projects_project_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag_name",
            field=models.TextField(max_length=200),
        ),
    ]
