# Generated by Django 4.1 on 2023-04-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_profile_options"),
        ("projects", "0006_alter_project_options_review_owner"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("owner", "project")},
        ),
    ]
