# Generated by Django 4.1 on 2023-04-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_review_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="featured_images",
            field=models.ImageField(
                blank=True,
                default="https://res.cloudinary.com/dnoomtyyx/image/upload/v1681232172/static/images/default.jpg",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
