# Generated by Django 4.1 on 2023-04-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_project_featured_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="featured_images",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="images/"
            ),
        ),
    ]
